# Generated by Django 3.1.3 on 2020-12-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default='9999-01-01')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default='9999-01-01')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navigation.department')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='navigation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default='9999-01-01')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navigation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorksAt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default='9999-01-01')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navigation.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navigation.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='works_at',
            field=models.ManyToManyField(through='navigation.EmployeeWorksAt', to='navigation.Department'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_name'),
        ),
    ]
