# Generated by Django 3.1.3 on 2020-12-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.employee'),
        ),
    ]
