# Generated by Django 3.1.3 on 2020-12-09 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20201206_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.department'),
        ),
    ]
