# Generated by Django 3.1.3 on 2020-12-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20201208_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
