# Generated by Django 3.1.3 on 2020-12-09 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.CharField(max_length=100)),
                ('sale_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='navigation.salestaff')),
            ],
        ),
    ]
