# Generated by Django 3.1.3 on 2020-12-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_order_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
    ]
