# Generated by Django 3.1.3 on 2020-12-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_systemuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
