# Generated by Django 3.1.3 on 2020-12-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_systemuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='access_level',
            field=models.CharField(choices=[('A', 'Admin'), ('G', 'Guest')], default='G', max_length=10),
        ),
    ]
